### ISSUE TITLE
Death Timer

### ISSUE THREAD

**Issue by BigBeastBrady** [CCM-Modding/Death-Timer#13]
2013-06-27 20:04:37 [INFO] [STDERR] java.lang.NullPointerException
2013-06-27 20:04:37 [INFO] [STDERR]     at ccm.deathTimer.timerTypes.PointTimer.getTimerString(PointTimer.java:103)
2013-06-27 20:04:37 [INFO] [STDERR]     at ccm.deathTimer.timerTypes.DeathTimer.getTimerString(DeathTimer.java:138)
2013-06-27 20:04:37 [INFO] [STDERR]     at ccm.deathTimer.client.HUD.doTimers(HUD.java:43)
2013-06-27 20:04:37 [INFO] [STDERR]     at ccm.deathTimer.client.HUD.render(HUD.java:32)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler_229_HUD_render_Text.invoke(.dynamic)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:39)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraftforge.event.EventBus.post(EventBus.java:108)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:606)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:133)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:999)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:871)
2013-06-27 20:04:37 [INFO] [STDERR]     at net.minecraft.client.Minecraft.run(Minecraft.java:760)
2013-06-27 20:04:37 [INFO] [STDERR]     at java.lang.Thread.run(Unknown Source)
2013-06-27 20:04:47 [INFO] [Minecraft-Client] Stopping!

**Comment by dries007** [comment]
Temp "fix" with try-catch loop.
