### ISSUE TITLE
crashed with a bunch of timers trying to find the max amount of time

### ISSUE THREAD

**Issue by Claycorp** [CCM-Modding/Death-Timer#9]
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
    at java.util.HashMap$ValueIterator.next(Unknown Source)
    at ccm.deathTimer.server.ServerTimer.tickStart(ServerTimer.java:50)
    at cpw.mods.fml.common.FMLCommonHandler.tickStart(FMLCommonHandler.java:122)
    at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:287)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:560)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:127)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

**Comment by Claycorp** [comment]
http://pastebin.com/62TqypAC
FML log

**Comment by dries007** [comment]
Whaat?

**Comment by CaptainShadows** [comment]
You are accessing something outside of the thread causing it to crash _Multi-Threading FTW_

**Comment by dries007** [comment]
I know what threading is, I'm just confused cause I don't thread anything
in this mod.
